#!/usr/bin/env python3
"""Bundle arena_results JSON files into dashboard/data.js."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "arena_results"
OUT = ROOT / "dashboard" / "data.js"

runs = []
for jf in sorted(RESULTS.glob("arena_*.json")):
    if "_report" in jf.stem:
        continue
    with open(jf) as f:
        data = json.load(f)
    runs.append({
        "id": jf.stem.replace("arena_", ""),
        "n_records": len(data),
        "data": data,
    })

with open(OUT, "w") as f:
    f.write("// Auto-generated by dashboard/build_data.py\n")
    f.write(f"window.ARENA_RUNS = {json.dumps(runs)};\n")

print(f"Wrote {OUT} ({OUT.stat().st_size / 1024:.1f} KB) — {len(runs)} runs")
