#!/usr/bin/env python3
"""Generate LaTeX table of main results from experiment JSON.

Usage:
    python scripts/generate_latex_table.py results/exp6_workshop_main/merged_results.json

Produces a ready-to-paste LaTeX table for the workshop paper, with:
- Rows: agents
- Columns: corruption types (clean, uniform, adversarial, consistently wrong)
- Values: mean +/- SE of final cumulative regret
- Bold for best agent per column
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
import numpy as np


AGENT_ORDER = [
    "llm_cucb_at",
    "cucb",
    "cts",
    "llm_greedy",
    "ellm_adapted",
    "warm_start_cts",
    "corrupt_robust_cucb",
    "exp4",
    "opro_bandit",
]

AGENT_LABELS = {
    "llm_cucb_at": "LLM-CUCB-AT (ours)",
    "cucb": "CUCB",
    "cts": "CTS",
    "llm_greedy": "LLM-Greedy",
    "ellm_adapted": "ELLM-Adapted",
    "opro_bandit": "OPRO-Bandit",
    "corrupt_robust_cucb": "Robust-CUCB",
    "warm_start_cts": "Warm-Start CTS",
    "exp4": "EXP4",
}

# Columns: (corruption_type, epsilon, display_name)
COLUMNS = [
    ("uniform", 0.0, "Clean ($\\varepsilon=0$)"),
    ("uniform", 0.1, "Uniform ($\\varepsilon=0.1$)"),
    ("adversarial", 0.3, "Advers.\\ ($\\varepsilon=0.3$)"),
    ("consistent_wrong", 1.0, "Consist.\\ Wrong"),
]


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/generate_latex_table.py <results.json> [--d D]")
        sys.exit(1)

    results_path = sys.argv[1]
    filter_d = None
    if "--d" in sys.argv:
        filter_d = int(sys.argv[sys.argv.index("--d") + 1])

    with open(results_path) as f:
        results = json.load(f)

    if filter_d:
        results = [r for r in results if r["d"] == filter_d]

    # Group by (agent, corruption_type, epsilon)
    groups = defaultdict(list)
    for r in results:
        key = (r["agent"], r["corruption_type"], r["epsilon"])
        groups[key].append(r["final_regret"])

    # Find best (lowest mean) per column
    best_per_col = {}
    for ct, eps, _ in COLUMNS:
        best_mean = float("inf")
        for agent in AGENT_ORDER:
            key = (agent, ct, eps)
            if key in groups:
                mean = np.mean(groups[key])
                if mean < best_mean:
                    best_mean = mean
                    best_per_col[(ct, eps)] = agent

    # Print header
    d_val = filter_d or (results[0]["d"] if results else "?")
    m_val = results[0]["m"] if results else "?"
    T_val = results[0]["T"] if results else "?"

    print("% Auto-generated by scripts/generate_latex_table.py")
    print(f"% Data: {results_path}, d={d_val}, m={m_val}, T={T_val}")
    print()
    print("\\begin{table}[t]")
    print("\\centering")
    print(f"\\caption{{Final cumulative regret (mean $\\pm$ SE, 30 seeds) on synthetic semi-bandits ($d={d_val}$, $m={m_val}$, $T={T_val:,}$).}}")
    print("\\label{tab:main_results}")
    print("\\small")
    col_spec = "l " + "c" * len(COLUMNS)
    print(f"\\begin{{tabular}}{{{col_spec}}}")
    print("\\toprule")

    # Column headers
    headers = ["Agent"] + [name for _, _, name in COLUMNS]
    print(" & ".join(headers) + " \\\\")
    print("\\midrule")

    # Rows
    for agent in AGENT_ORDER:
        if agent not in {r["agent"] for r in results}:
            continue
        label = AGENT_LABELS.get(agent, agent)
        cells = [label]
        for ct, eps, _ in COLUMNS:
            key = (agent, ct, eps)
            if key in groups:
                vals = groups[key]
                mean = np.mean(vals)
                se = np.std(vals) / np.sqrt(len(vals))
                cell = f"{mean:.0f} $\\pm$ {se:.0f}"
                if best_per_col.get((ct, eps)) == agent:
                    cell = f"\\textbf{{{cell}}}"
                cells.append(cell)
            else:
                cells.append("---")
        print(" & ".join(cells) + " \\\\")

    print("\\bottomrule")
    print("\\end{tabular}")
    print("\\end{table}")


if __name__ == "__main__":
    main()
